version: '3.8'

services:
  api:
    build: .
    container_name: empleados-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/app/logs